services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: crikverse
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123#@

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - crikverse-network

  backend-api:
    image: crikverse-server-main:0.2
    container_name: backend-api
    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "8001:8000"

    volumes:
      - ./env/crikverse-server/.env:/app/.env:ro

    networks:
      - crikverse-network

  socket:
    image: crikverse-socket:0.1
    container_name: socket
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./env/socket/.env:/app/.env:ro
    networks:
      - crikverse-network

  backend-admin:
    image: superadmin:0.1
    container_name: backend-admin
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - "8002:8002"
    volumes:
      - ./env/superadmin-backend/.env:/app/.env:ro
    networks:
      - crikverse-network

volumes:
  postgres_data:

networks:
  crikverse-network:
    driver: bridge
