name: Application Security

on:
  push:
  pull_request:

permissions:
  contents: read
  actions: read
  security-events: write

jobs:
  security:
    uses: chandru05092001/devsecops-workflows/.github/workflows/devsecops.yaml@main

    with:
      sonar_project_key: chandru05092001_devsecops-demo-app
      sonar_organization: chandru05092001
      codeql_languages: python

    secrets: inherit
